include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
    - '**.pb.dart'
    - '**.pbenum.dart'
    - '**.pbgrpc.dart'
    - '**.pbjson.dart'