name: finflow_backend
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1
dependencies:
  googleapis_auth: ^1.3.1
  grpc: ^3.1.0
  jwt_decoder: ^2.0.1
  protobuf: ^2.1.0
